### ISSUE TITLE
Limits of wavelength_micron.inp and plotting problems

### ISSUE THREAD

**Issue by rgalvanmadrid** [andizq/sf3dmodels#7]
While running the scripts in /star-forming-regions/examples/ionized_powerlaw, ramdc gives this warning and doesn't run: 
Reading global frequencies/wavelengths...
 ***************************************************************
 WARNING: While reading wavelength data from wavelength_micron.inp
          Wavelength range does not extend to < 1 micron.
          In virtually all applications this means that the 
          starlight is not covered... Are you sure this is OK??
 ***************************************************************

Which would make sense for a star+dust case, but not for a free-free calculation in the cm continuum. 

I was considering editing write_wavelength_micron in ./sf3dmodels/rt/core.py but I'm unsure if this would be the right approach, or better solving something with RADMC?

A different problem in the same example. The plotting commands in ExecModel_plsphere.py give errors like: 

-------------------------------------------------
-------------------------------------------------
Plotting 3D model with 4000 random-weighted points...
3D camera azimuth: -60.0 deg
3D camera elevation: 30.0 deg
Image saved as 3Ddens_plsphere_HII.png
Ellapsed time from scatter3D: 2.63 s
The show-image mode is off!
scatter3D is done!
-------------------------------------------------
-------------------------------------------------
Plotting 3D model with 4000 random-weighted points...
3D camera azimuth: -60.0 deg
3D camera elevation: 30.0 deg
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/myscisoft/star-forming-regions/examples/ionized_powerlaw/ExecModel_plsphere.py in <module>
     78 
     79 Plot_model.scatter3D(GRID, density.total, weight, NRand = 4000, colordim = temperature.total, axisunit = u.au, cmap = 'binary', marker = 'o', s = 4,
---> 80                      colorscale = 'uniform', colorlabel = r'$T_{\rm e}$ [Kelvin]', output = '3Dtemp_%s.png'%tag, show = False)
     81 
     82 

~/anaconda3/lib/python3.7/site-packages/sf3dmodels-0.0.dev1295-py3.7.egg/sf3dmodels/Plot_model.py in scatter3D(GRID, prop, weight, colordim, NRand, axisunit, power, colorlabel, output, show, colorscale, azim, elev, xlim, ylim, zlim, **kwargs)
    274 
    275     plt.tight_layout()
--> 276     plt.savefig(output, dpi = 1000)
    277     print ('Image saved as %s'%output)
    278     print ("Ellapsed time from %s: %.2f s"%(inspect.stack()[0][3], time.time()-t0))

~/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py in savefig(*args, **kwargs)
    727 def savefig(*args, **kwargs):
    728     fig = gcf()
--> 729     res = fig.savefig(*args, **kwargs)
    730     fig.canvas.draw_idle()   # need this if 'transparent=True' to reset colors
    731     return res

~/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py in savefig(self, fname, transparent, **kwargs)
   2178             self.patch.set_visible(frameon)
   2179 
-> 2180         self.canvas.print_figure(fname, **kwargs)
   2181 
   2182         if frameon:

~/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, **kwargs)
   2089                     orientation=orientation,
   2090                     bbox_inches_restore=_bbox_inches_restore,
-> 2091                     **kwargs)
   2092             finally:
   2093                 if bbox_inches and restore_bbox:

~/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py in print_png(self, filename_or_obj, metadata, pil_kwargs, *args, **kwargs)
    525 
    526         else:
--> 527             FigureCanvasAgg.draw(self)
    528             renderer = self.get_renderer()
    529             with cbook._setattr_cm(renderer, dpi=self.figure.dpi), \

~/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    386         self.renderer = self.get_renderer(cleared=True)
    387         with RendererAgg.lock:
--> 388             self.figure.draw(self.renderer)
    389             # A GUI class may be need to update a window using this draw, so
    390             # don't forget to call the superclass.

~/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

~/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py in draw(self, renderer)
   1707             self.patch.draw(renderer)
   1708             mimage._draw_list_compositing_images(
-> 1709                 renderer, self, artists, self.suppressComposite)
   1710 
   1711             renderer.close_group('figure')

~/anaconda3/lib/python3.7/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    133     if not_composite or not has_images:
    134         for a in artists:
--> 135             a.draw(renderer)
    136     else:
    137         # Composite any adjacent images together

~/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     36                 renderer.start_filter()
     37 
---> 38             return draw(artist, renderer, *args, **kwargs)
     39         finally:
     40             if artist.get_agg_filter() is not None:

~/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py in draw(self, renderer)
    290                 sorted(self.collections,
    291                        key=lambda col: col.do_3d_projection(renderer),
--> 292                        reverse=True)):
    293             col.zorder = zorder_offset + i
    294         for i, patch in enumerate(

~/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/axes3d.py in <lambda>(col)
    289         for i, col in enumerate(
    290                 sorted(self.collections,
--> 291                        key=lambda col: col.do_3d_projection(renderer),
    292                        reverse=True)):
    293             col.zorder = zorder_offset + i

~/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/art3d.py in do_3d_projection(self, renderer)
    543         self.set_facecolors(fcs)
    544 
--> 545         ecs = (_zalpha(self._edgecolor3d, vzs) if self._depthshade else
    546                self._edgecolor3d)
    547         ecs = mcolors.to_rgba_array(ecs, self._alpha)

~/anaconda3/lib/python3.7/site-packages/mpl_toolkits/mplot3d/art3d.py in _zalpha(colors, zs)
    845     norm = Normalize(min(zs), max(zs))
    846     sats = 1 - norm(zs) * 0.7
--> 847     rgba = np.broadcast_to(mcolors.to_rgba_array(colors), (len(zs), 4))
    848     return np.column_stack([rgba[:, :3], rgba[:, 3] * sats])
    849 

<__array_function__ internals> in broadcast_to(*args, **kwargs)

~/anaconda3/lib/python3.7/site-packages/numpy/lib/stride_tricks.py in broadcast_to(array, shape, subok)
    180            [1, 2, 3]])
    181     """
--> 182     return _broadcast_to(array, shape, subok=subok, readonly=True)
    183 
    184 

~/anaconda3/lib/python3.7/site-packages/numpy/lib/stride_tricks.py in _broadcast_to(array, shape, subok, readonly)
    125     it = np.nditer(
    126         (array,), flags=['multi_index', 'refs_ok', 'zerosize_ok'] + extras,
--> 127         op_flags=['readonly'], itershape=shape, order='C')
    128     with it:
    129         # never really has writebackifcopy semantics

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (0,4) and requested shape (4000,4)

**Comment by andizq** [comment]
Thanks for raising this issue. I think that radmc3d warns about this regardless of the RT mode you choose, any case I extended the wavelength grid on rt/core.py for the freefree mode as well (see https://github.com/andizq/star-forming-regions/commit/865eeda887d1243a45c8b3755bd9a7a748020e1f). Alternatively you can modify your wavelength limits and steps using the freefree() command kwargs in your exec script (see the updated example on ionized_powerlaw/).

As for the plotting error, it's apparently something to do with the latest Matplotlib+Numpy dependencies unable to handle filled markers such as 'o' or 'D' in 3d projections. For the moment please use unfilled markers e.g.  '.'  '+' or 'x'. Also updated on https://github.com/andizq/star-forming-regions/commit/865eeda887d1243a45c8b3755bd9a7a748020e1f
